### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by gedw99** [txthinking/nami#26]
https://github.com/aquaproj/aqua is golang and has a markup language but also has versioning.

there is also a registry, so you can declare the mapping the name to where the binary is stored. the registry is just a github repo.

Its pretty good. takes a while to get used to its cli.

**Comment by gedw99** [comment]
> actually, I haven't used github action, I think its concepts and syntax are a bit too much, so I didn't learn it. Does aqua have to work with github action?
> by [unknown](https://t.me/brookgroup)

no. Its just an example of how it can be used.

**Comment by gedw99** [comment]
there are 3 downloads which are golang.

aqua is a general command for using aqua.

aqua-proxy if on any computer, allows you to call a binary that is not there yet, by version. it will download it and then let the command call through to the binary. Its doing exactly what "serverless" does.

aqua-registry allow you to submit any binary to the registry. So its for devs.

 

```sh
	# https://github.com/aquaproj/aqua
	go install github.com/aquaproj/aqua/v2/cmd/aqua@latest
	
	# https://github.com/aquaproj/aqua-proxy
	go install github.com/aquaproj/aqua-proxy/cmd/aqua-proxy@latest

	# https://github.com/aquaproj/registry-tool
	go install github.com/aquaproj/registry-tool/cmd/aqua-registry@latest

```

All the packages are here: 
# the github registry
# all inside at https://github.com/aquaproj/aqua-registry/tree/main/pkgs
# https://github.com/aquaproj/aqua-registry

if you just look inside one you can see how you describe a package

example of how the registry works.

https://github.com/99designs/aws-vault wants to be put into aqua

https://github.com/aquaproj/aqua-registry/blob/main/pkgs/99designs/aws-vault/pkg.yaml
```yaml
packages:
  - name: 99designs/aws-vault@v7.2.0
  - name: 99designs/aws-vault
    version: v6.5.0
  - name: 99designs/aws-vault
    version: v6.3.0
  - name: 99designs/aws-vault
    version: v5.2.0
  - name: 99designs/aws-vault
    version: v5.1.0
  - name: 99designs/aws-vault
    version: v4.7.0
  - name: 99designs/aws-vault
    version: v3.5.0
  - name: 99designs/aws-vault
    version: v3.0.0-dev
  - name: 99designs/aws-vault
    version: v2.4.0
  - name: 99designs/aws-vault
    version: v2.3.3
  - name: 99designs/aws-vault
    version: v2.3.2
  - name: 99designs/aws-vault
    version: v1.0.0
```

https://github.com/aquaproj/aqua-registry/blob/main/pkgs/99designs/aws-vault/registry.yaml
```yaml

packages:
  - type: github_release
    repo_owner: 99designs
    repo_name: aws-vault
    description: A vault for securely storing and accessing AWS credentials in development environments
    asset: aws-vault-{{.OS}}-{{.Arch}}
    format: raw
    overrides:
      - goos: darwin
        format: dmg
        asset: aws-vault-{{.OS}}-{{.Arch}}.{{.Format}}
    supported_envs:
      - linux
      - darwin
      - windows/arm64
    checksum:
      type: github_release
      asset: SHA256SUMS
      algorithm: sha256
    version_constraint: semver(">= 6.5.0")
    version_overrides:
      - version_constraint: semver(">= 6.3.0")
        asset: aws-vault-{{.OS}}-{{.Arch}}.{{.Format}}
        format: dmg
        overrides:
          - goos: linux
            format: raw
            asset: aws-vault-{{.OS}}-{{.Arch}}
        supported_envs:
          - linux
          - darwin
      - version_constraint: semver(">= 5.2.0")
        asset: aws-vault-{{.OS}}-{{.Arch}}.{{.Format}}
        format: dmg
        overrides:
          - goos: linux
            format: raw
            asset: aws-vault-{{.OS}}-{{.Arch}}
        supported_envs:
          - linux
          - darwin
        rosetta2: true
      - version_constraint: semver(">= 5.1.0")
        asset: aws-vault-{{.OS}}-{{.Arch}}.{{.Format}}
        format: dmg
        overrides:
          - goos: linux
            format: raw
            asset: aws-vault-{{.OS}}-{{.Arch}}
        supported_envs:
          - linux
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 4.7.0")
        asset: aws-vault-{{.OS}}-{{.Arch}}.{{.Format}}
        format: dmg
        overrides:
          - goos: linux
            format: raw
            asset: aws-vault-{{.OS}}-{{.Arch}}
        supported_envs:
          - linux/amd64
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 3.5.0")
        overrides: []
        supported_envs:
          - linux/amd64
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 3.0.0-dev")
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
        supported_envs:
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 2.4.0")
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
        supported_envs:
          - linux/amd64
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 2.3.3")
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
        supported_envs:
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver(">= 2.3.2")
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
          linux: Linux
        supported_envs:
          - linux/amd64
          - darwin
        rosetta2: true
        checksum:
          enabled: false
      - version_constraint: semver("< 2.3.2")
        overrides: []
        replacements:
          amd64: x86_64
          darwin: Darwin
        supported_envs:
          - darwin
        rosetta2: true
        checksum:
          enabled: false
```
